spring.application.name=banco_digital_api
server.port=8081

# Supabase PostgreSQL Configuration (IPv4 / Connection Pooler) - DISABLED
# spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true
# spring.datasource.driverClassName=org.postgresql.Driver
# spring.datasource.username=postgres.zqjxmrtezichbtqbjpcy
# spring.datasource.password=SomosGrupo2
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# H2 Local Configuration
spring.datasource.url=jdbc:h2:file:./data/banco_digital_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console enabled
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.datasource.hikari.maximum-pool-size=1

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
jwt.secret=94f28aa2998a183863aae2a87d4681f215ce82e6669894e48b813fdc2b7fc068d89163e9f02c63fdd2fc4ff99cb8df10fd296efb21af20b4142f88ff05b38ed6
jwt.expiration=86400000

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Ajustes de Correo (Spring Mail - Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:tu_correo@gmail.com}
spring.mail.password=${MAIL_PASSWORD:tu_contraseña_de_aplicacion}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
